<h1>Evidence kosmonautů</h1> 
<table>
 <thead>    
    <tr><th>Jméno</th><th>Příjmení</th><th>Datum narození</th><th>Superschopnost</th><?php if ($admin) : ?><th colspan="2">Administrace</th><?php endif ?>
    </tr>   
 </thead>
 <tbody>
   <?php foreach ($cosmonauts as $cosmonaut) : ?>                                                                  
    <tr><td><?=$cosmonaut['jmeno']?></td><td><?=$cosmonaut['prijmeni']?></td><td><?=DatumHelper::datumCzech($cosmonaut['datum_narozeni'])?></td>
        <td><?=$cosmonaut['superschopnost']?></td>
        
      <?php if ($admin) : ?><td><a href="editing/<?= $cosmonaut['kosmonaut_id'] ?>">Editovat</a></td>
                        <td><a href="cosmonaut/<?= $cosmonaut['kosmonaut_id'] ?>/delete">Odstranit</a></td>
      <?php endif ?>
      
    </tr>
   <?php endforeach ?>                    
 </tbody>   
</table> 