<!DOCTYPE html>
<html lang="cs-cz">
    <head>
            <base href="/localhost" />
            <meta charset="UTF-8" />
            <title><?= $title ?></title>
            <meta name="description" content="<?= $description ?>" />
            <meta name="keywords" content="<?= $keywords ?>" />
            <link rel="stylesheet" href="style.css" type="text/css"/>
    </head>

    <body>
            <header>
                    <h1>Elektronická evidence kosmonautů</h1>
            </header>
            <?php foreach ($messages as $message) : ?>
            <p class="message"><?= $message ?></p>
            <?php endforeach ?>
            <nav>
                <ul>                                     
                    <li><a href="cosmonaut">Přehled</a></li>
                    <li><a href="administration">Administrace</a>
                    <li><a href="contact">Kontakt</a></li>   
                </ul>
            </nav>
                <br clear="both" />

            <article>
                    <?php $this->controller->renderView(); ?>
            </article>

            <footer>
                    <p>Electronic evidence based on MVC architecture
                    <a href="http://www.itnetwork.cz" target="_blank">itnetwork.cz</a>.</p>
                    <a href="administrace">Administrace</a>
            </footer>
    </body>
</html>