<h1>Registrace</h1>

<form method="post">
        Jméno<br />
        <input type="text" name="name" /><br />
        Heslo<br />
        <input type="password" name="password" /><br />
        Heslo znovu<br />
        <input type="password" name="confirm_password" /><br />
        Zadejte aktuální rok (antispam)<br />
        <input type="text" name="rok" /><br />
        <input type="submit" value="Registrovat" />
</form>